### ISSUE TITLE
[FEATURE] Scrapped page layout option

### ISSUE THREAD

**Issue by LorenaGambarrota** [yamilt351/scraper#105]

**Comment by yamilt351** [comment]
i wanna know how related results will display with this template? 
Are contents going to be displayed on the side?

**Comment by LorenaGambarrota** [comment]
Yes, it could be as you say. Or else another option is that all the searches are in the small cards, and when you select one, you can see it larger on the side. And that gives you a preview of the news, without having to click and redirect the web.

**Comment by yamilt351** [comment]
u mean something like this? 
![image](https://github.com/yamilt351/scraper/assets/88646148/f0f7b38e-7dc9-4ce9-95cd-9bb51b9d2834)

**Comment by yamilt351** [comment]
im doing this in this way 
![image](https://github.com/yamilt351/scraper/assets/88646148/26369426-c57c-48af-aeb0-1b6a466c952f)

**Comment by LorenaGambarrota** [comment]
[Op2.pdf](https://github.com/yamilt351/scraper/files/12362230/Op2.pdf)

**Comment by LorenaGambarrota** [comment]
![Opcion2 ](https://github.com/yamilt351/scraper/assets/126104822/95f6ba2c-e5a1-4b89-9fce-655059a42adc)

**Comment by LorenaGambarrota** [comment]
Maybe something like this can be seen more orderly. And in this way, if there are many articles, you can generate a more important preselection in the first line, which can be moved to the side.

**Comment by LorenaGambarrota** [comment]
what do you think? color theme I am respecting the ones you have shown me, I did not want to touch much more ... only design

**Comment by yamilt351** [comment]
![image](https://github.com/yamilt351/scraper/assets/88646148/13d005b0-5e9d-415c-a916-183ef7cfeb62)

let's go with this design, looks so polish and clean i love it!. About theming... i dont mind about colors, is something easily to change and reasign so to me is something with no importance , but if you wanna change the color scheme to another more smooth feel free to do that, meanwhile i will add you to `colaborators`section bc i will use this design ! 
just one thing , where related results will display with this design?

**Comment by yamilt351** [comment]
if you wanna change something like buttons or what ever you want feel free to make your suggestions!

**Comment by LorenaGambarrota** [comment]
I'm glad you like it and it works for you!

**Comment by LorenaGambarrota** [comment]
About the color, I was only asking because I saw that you had changed to a darker blue in an example, but you're right! for that there is still time and it is the easiest

**Comment by LorenaGambarrota** [comment]
And I think that I still maintain the idea of ​​expanding the news by a hover so that the user sees a little more, without the need to click. What do you think?

**Comment by yamilt351** [comment]
something like this but with the article content ?
![image](https://github.com/yamilt351/scraper/assets/88646148/30f9f586-bb4a-4770-9318-3b2d39e949c0)

**Comment by yamilt351** [comment]
![image](https://github.com/yamilt351/scraper/assets/88646148/d0c3d6e0-5f61-4d12-bacb-0b0cbe54bfa5)

**Comment by yamilt351** [comment]
the height should be auto? or fixed?
