### ISSUE TITLE
[TASK] Change Date format 

### ISSUE THREAD

**Issue by yamilt351** [yamilt351/scraper#113]
change date format for scanned webpage updatedAt

![image](https://github.com/yamilt351/scraper/assets/88646148/46cca5ed-7b39-486e-9085-2dc7df836b1e)

files: scrapper.js 
function : createScrappedResults

code snippet:

const dateISO = "2023-08-17T19:51:37.734Z";
const date = new Date(dateISO);

const day= date.getDate();
const month = date.getMonth() + 1;  
const year = date.getFullYear();

**Comment by Bolaji06** [comment]
Will like to work on this issue

**Comment by Bolaji06** [comment]
> Will like to work on this issue

Can you assign me to it?

**Comment by yamilt351** [comment]
Hello and welcome! i assigned this task to you!

**Comment by Bolaji06** [comment]
This are couple of issues I saw on the homepage 
<img width="413" alt="Screenshot 2023-08-17 235850" src="https://github.com/yamilt351/scraper/assets/40664855/e9719cf2-3e71-4a52-8d4c-c84702854d65">
The bottom of the button is cut-out and the shadow is relatively too much

**Comment by yamilt351** [comment]
ya, dont worry for that !

**Comment by Bolaji06** [comment]
Alright

**Comment by Bolaji06** [comment]
> change date format for scanned webpage updatedAt
> 
> ![image](https://user-images.githubusercontent.com/88646148/261422265-46cca5ed-7b39-486e-9085-2dc7df836b1e.png)
> 
> files: scrapper.js function : createScrappedResults
> 
> code snippet:
> 
> const dateISO = "2023-08-17T19:51:37.734Z"; const date = new Date(dateISO);
> 
> const day= date.getDate(); const month = date.getMonth() + 1; const year = date.getFullYear();

The date should be in this format I guess: 17-08-2023

**Comment by yamilt351** [comment]
ya or 17/08/2023 up to you

**Comment by Bolaji06** [comment]
Just sent a PR on this issue
