### ISSUE TITLE
[TASK] Rename buttons legends in <export section>

### ISSUE THREAD

**Issue by yamilt351** [yamilt351/scraper#74]
![image](https://github.com/yamilt351/scraper/assets/88646148/259044f3-1a38-42be-bbed-a99d5c1d10a4)
![image](https://github.com/yamilt351/scraper/assets/88646148/1a1eb3cb-aeec-4985-9e30-1e2a2949ab21)
![image](https://github.com/yamilt351/scraper/assets/88646148/d4d839e6-69a8-4467-9a72-7d7b77a08c98)

Those legends buttons (more info) must say something like , try now or start now , in others words must be a call to action

**Comment by 2div** [comment]
Hi,
I would like to handle this task if not assigned to anyone yet.
I understand that you want to edit the 3 buttons text to Start Now . 
Please confirm ?

**Comment by yamilt351** [comment]
hello again! , done

**Comment by yamilt351** [comment]
> Hi, I would like to handle this task if not assigned to anyone yet. I understand that you want to edit the 3 buttons text to Start Now . Please confirm ?

`` I understand that you want to edit the 3 buttons text to Start Now ``
yes, exactly like that
