### ISSUE TITLE
[TASK] scroll behaviour smooth

### ISSUE THREAD

**Issue by yamilt351** [yamilt351/scraper#76]
```
html {
  scroll-behavior: smooth;
}
```
add this snippet code into styles.css

**Comment by 2div** [comment]
Hi , if no one working on this task , can you assign it to me ?

**Comment by yamilt351** [comment]
Hello!, yes i can assign this task to you, but remember please make one pr per task, dont put multiples tasks in one big pr

**Comment by yamilt351** [comment]
this task was done by other user, i will close this issue.
