### ISSUE TITLE
[TASK] Replace "Contact" with "Features"

### ISSUE THREAD

**Issue by yamilt351** [yamilt351/scraper#91]
## Task Description
Replace Contact  section and it's external link for "Features" and it's internal link
![image](https://github.com/yamilt351/scraper/assets/88646148/690ce6b5-46a9-45b8-884c-fb0bafad13d2)
![image](https://github.com/yamilt351/scraper/assets/88646148/071e180f-c869-41d9-81e7-4d2f5e101584)

**Comment by Piyush-Deshmukh** [comment]
Hey there, can you assign me this issue and also tell the FEATURES link ?

**Comment by yamilt351** [comment]
Hello! thanks for your interest in this project!.
there's no link, is an internal link, to `features-container` section, you probably need's to add an `id` to that container.
