### ISSUE TITLE
[TASK] add shadow box to navbar

### ISSUE THREAD

**Issue by yamilt351** [yamilt351/scraper#92]
## Task Description

apply shadow-box property to navbar the shadow box should be smooth  but enough to differentiate  navbar from body, and should not be too

## Steps to Follow

1. you can use something like this for example 
```
box-shadow: 0px 4px 5px 0px rgba(82,82,82,0.75);
-webkit-box-shadow: 0px 4px 5px 0px rgba(82,82,82,0.75);
-moz-box-shadow: 0px 4px 5px 0px rgba(82,82,82,0.75);

```

## Acceptance Criteria

- The shaodwbox must be replace it by the progress scroll bar
- The shadowbox should be clear enough to differentiate navbar from body
- your pr must contain at least 1 screenshot per web page section 

## More options
- im open to new suggestions / opinions

**Comment by Rayen-Allaya** [comment]
Hello ! 
I want to adress this task 
But i just wanted some clarification:
Do you want to remove the progress bar and change it by the box shadow or do you want to keep them both ? 
Thank you !

**Comment by yamilt351** [comment]
Hello! and welcome!.
Sorry if i was not clear enough about this task. 
I want fix this behavior 
![image](https://github.com/yamilt351/scraper/assets/88646148/9de25cb0-1a75-4be5-a91d-102ca9c9d211)

So, i want to keep them both
