### ISSUE TITLE
[BUG] Hamburger menu not filling the whole screen

### ISSUE THREAD

**Issue by Rayen-Allaya** [yamilt351/scraper#94]
When you open the hamburger menu in the small screen you can see a gap at the bottom of the page.
I think it should fill the whole page

![image](https://github.com/yamilt351/scraper/assets/118576115/9f62420a-849c-44ad-be96-f7f58fa0b3d1)

**Comment by yamilt351** [comment]
Ty! for your report

**Comment by yamilt351** [comment]
can u tell me please what resolution did you used it?

**Comment by Rayen-Allaya** [comment]
Hii
It just appeared on my laptop which is 1368x768
But i think you just need specify the height as 100vh so it works for every device
